### ISSUE TITLE
How to change width of pages / sidebars?

### ISSUE THREAD

**Issue by MonikaBarget** [jasonlong/tactile-theme#4]
I like the Tactile theme very much and have used it to create this deployment:

https://monikabarget.github.io/Revolts/

Unfortunately, I am struggling with the width of the body and / or the "sidebars" on the left and right. The text itself is obviously marked-up in a `<section>` tag, but I could not find any indication in the CSS files why only about half of the available screen space is used.

As soon as I integrate items such as HMTL tables, the full width of the page is different, cf. 

https://monikabarget.github.io/Revolts/event-table.html

If anyone can point me to the correct section in the Jekyll CSS, I would be more than grateful.

**Comment by jasonlong** [comment]
Hi @MonikaBarget :wave:

This theme is really old, but I'm happy to hear you're still making use of it. If you're just looking to widen the main content area, you should be able to simply tweak the width in the `.inner` class.

https://github.com/jasonlong/tactile-theme/blob/e1130f966c0f684c97a66a879df64a7d7168deaa/stylesheets/stylesheet.css#L92-L95
